version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL_PORT=3000
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
